name: gh2

on:
  pull_request:
    branches:
      - main


jobs:
  dinkchika:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: hellobro
        run: |
          echo ' hello vinay'
          pwd